// Generated by CoffeeScript 1.10.0
var FFMPEG, colors, ffmpeg, path, shell;

colors = require('colors');

ffmpeg = require('fluent-ffmpeg');

shell = require('shelljs');

path = require('path');

FFMPEG = {
  convert: function(options) {
    var format, input, output;
    input = options.input;
    format = options.format;
    output = options.output;
    return new Promise(function(resolve, reject) {
      var binary, proc;
      if (!format) {
        reject({
          msg: "Error: Please provide a format",
          error: true
        });
      }
      if (!output) {
        output = path.parse(input);
        output = path.join(output.dir, output.name + "." + format);
      }
      binary = shell.which('ffmpeg');
      binary = "" + binary;
      proc = new ffmpeg({
        source: input,
        nolog: true
      });
      return proc.setFfmpegPath(binary).toFormat(format).on('end', function() {
        return resolve({
          msg: "File: " + input + " has been converted successfully"
        });
      }).on('error', function(err) {
        return resolve({
          msg: 'An error happened',
          error: err.message
        });
      }).saveToFile(output);
    });
  }
};

module.exports = FFMPEG;
